### ISSUE TITLE
react/avatar

### ISSUE THREAD

**Issue by TheDim0n** [RTUITLab/ITLab-Core-Lib#71]
- [ ] обрезать или растягивать картинку

**Comment by IvLaptev** [comment]
Вот пример того, как туда вставилась картинка
![image](https://user-images.githubusercontent.com/23360152/212088004-04e93591-3e88-40c6-93c8-dc7861b2f020.png)

**Comment by IvLaptev** [comment]
На самом деле, если почитать, что написано в фигме (рис. 1), то получится, что кроме текста и картинки в аватаре не может быть ничего. То есть нет смысла передавать туда `children`. Вместо этого достаточно использовать один атрибут для передачи текста и один для передачи ссылки. Мне так кажется.

![image](https://user-images.githubusercontent.com/23360152/212110752-5aee5d3c-4602-4cca-83ac-1bb2096fd36b.png)
